"""Small DB-API boundary. Database objects belong to a runtime, never a global registry."""
from __future__ import annotations

import re
import sqlite3
from math import ceil
from pathlib import Path
from threading import Lock

from .config import DatabaseSettings, parse_database_settings


class StorageError(RuntimeError):
    pass


class StorageIntegrityError(StorageError):
    pass


# Fixed namespace shared by API, bot, migrations, and import tooling.
WRITE_LOCK = 240_001
IDENTITY_TABLES = frozenset({
    "auth_accounts", "organizations", "organization_invitations", "company_workspaces",
    "tenders", "saved_opportunities", "discovery_search_history", "support_tickets",
    "support_ticket_messages", "rag_chunks",
})


def identifier(value: str) -> str:
    # Catalog names are still untrusted SQL identifiers; quote or reject them.
    if not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", value):
        raise StorageError("Unsupported database identifier.")
    return '"' + value + '"'


def postgres_sql(sql: str, *, parameters: bool = True) -> str:
    """Compile the project's controlled SQL subset; leave quoted literals untouched."""
    # DDL remains deliberately compatible with integer flags and exact ISO timestamp strings.
    parts = re.split(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\")", sql)
    for i in range(0, len(parts), 2):
        part = re.sub(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
                      "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", parts[i], flags=re.I)
        part = re.sub(r"\bINTEGER\b", "BIGINT", part, flags=re.I)
        part = re.sub(r"\bBLOB\b", "BYTEA", part, flags=re.I)
        parts[i] = re.sub(r"\s+COLLATE\s+NOCASE", "", part, flags=re.I)
    sql = "".join(parts)
    ignore = bool(re.match(r"\s*INSERT\s+OR\s+IGNORE\b", sql, re.I))
    if ignore:
        sql = re.sub(r"INSERT\s+OR\s+IGNORE", "INSERT", sql, count=1, flags=re.I)
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    if parameters:
        sql = sql.replace("%", "%%")
        parts = re.split(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\")", sql)
        sql = "".join(p if i % 2 else p.replace("?", "%s")
                      for i, p in enumerate(parts))
    return sql


class Row(dict):
    def __getitem__(self, key):
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)


class Cursor:
    def __init__(self, raw, call, *, inserted_id=None):
        self.raw = raw
        self._call = call
        self.lastrowid = inserted_id
        self.rowcount = raw.rowcount

    def fetchone(self):
        row = self._call(self.raw.fetchone)
        return Row(row) if row is not None else None

    def fetchall(self):
        return [Row(row) for row in self._call(self.raw.fetchall)]

    def __iter__(self):
        return iter(self.fetchall())


class PostgresConnection:
    def __init__(self, database, raw):
        self.database, self.raw = database, raw
        self.pool = database.pool
        self.closed = False
        self.locked = False

    def _call(self, action):
        try:
            return action()
        except self.database.integrity_error:
            raise StorageIntegrityError("Database constraint violation.") from None
        except Exception:
            raise StorageError("Database operation failed.") from None

    def lock_write(self):
        if not self.locked:
            self._call(lambda: self.raw.execute("SELECT pg_advisory_xact_lock(%s)", (WRITE_LOCK,)))
            self.locked = True

    def execute(self, sql, params=()):
        if sql.strip().upper() in {"BEGIN", "BEGIN IMMEDIATE"}:
            self.lock_write()
            return None
        compiled = postgres_sql(sql, parameters=bool(params))
        match = re.match(r"\s*INSERT\s+INTO\s+(\w+)\b", compiled, re.I)
        returning = match and match[1] in IDENTITY_TABLES and "RETURNING" not in compiled.upper()
        if returning:
            compiled = compiled.rstrip().rstrip(";") + " RETURNING id"
        raw = self._call(lambda: self.raw.execute(compiled, params or None))
        inserted_id = None
        if returning:
            row = self._call(raw.fetchone)
            inserted_id = row["id"] if row else None
        return Cursor(raw, self._call, inserted_id=inserted_id)

    def executemany(self, sql, params):
        cursor = self._call(self.raw.cursor)
        try:
            self._call(lambda: cursor.executemany(postgres_sql(sql), params))
        finally:
            self._call(cursor.close)

    def executescript(self, sql):
        # Fixed migration scripts contain no procedural bodies or semicolons in literals.
        for statement in sql.split(";"):
            if statement.strip():
                self.execute(statement)

    def commit(self):
        self._call(self.raw.commit)
        self.locked = False

    def rollback(self):
        self._call(self.raw.rollback)
        self.locked = False

    def __enter__(self):
        self.lock_write()
        return self

    def __exit__(self, kind, value, traceback):
        if kind is None:
            self.commit()
        else:
            self.rollback()

    def close(self):
        if not self.closed:
            self.closed = True
            try:
                self.raw.rollback()
            except Exception:
                self._call(self.raw.close)
            finally:
                self._call(lambda: self.pool.putconn(self.raw))


class Database:
    def __init__(self, settings: DatabaseSettings, *, pool_factory=None):
        self.settings = settings
        self.pool = None
        self._pool_factory = pool_factory
        self._lock = Lock()
        self._closed = False
        self.integrity_error = ()

    @property
    def backend(self):
        return self.settings.backend

    def open(self):
        with self._lock:
            if self._closed:
                raise StorageError("Database is closed.")
            if self.backend == "sqlite" or self.pool is not None:
                return
            try:
                factory = self._pool_factory
                if factory is None:
                    from psycopg import Connection, IntegrityError, OperationalError
                    from psycopg.rows import dict_row
                    from psycopg_pool import ConnectionPool
                    self.integrity_error = IntegrityError
                    factory = ConnectionPool
                    kwargs = {"row_factory": dict_row, "connect_timeout": max(1, ceil(self.settings.pool_timeout))}
                    class SafeConnection(Connection):
                        def __repr__(self):
                            return "<VALYQON PostgreSQL connection>"

                        @classmethod
                        def connect(cls, *args, **kwargs):
                            try:
                                return super().connect(*args, **kwargs)
                            except Exception:
                                # The pool logs connection retry exceptions. Redact before
                                # they reach the official pool's background threads.
                                raise OperationalError("PostgreSQL connection unavailable.") from None
                    pool_options = {"connection_class": SafeConnection}
                else:
                    kwargs = {}
                    pool_options = {}
                self.pool = factory(
                    conninfo=self.settings.url, min_size=self.settings.pool_min,
                    max_size=self.settings.pool_max, timeout=self.settings.pool_timeout,
                    kwargs=kwargs, open=False, **pool_options,
                )
                self.pool.open(wait=True, timeout=self.settings.pool_timeout)
            except Exception:
                if self.pool is not None:
                    try:
                        self.pool.close()
                    except Exception:
                        pass
                self.pool = None
                raise StorageError("PostgreSQL unavailable; verify database configuration and dependencies.") from None

    def connect(self):
        self.open()
        if self.backend == "sqlite":
            conn = sqlite3.connect(self.settings.path, timeout=10)
            conn.row_factory = sqlite3.Row
            conn.execute("PRAGMA foreign_keys=ON")
            return conn
        try:
            return PostgresConnection(self, self.pool.getconn(timeout=self.settings.pool_timeout))
        except Exception:
            raise StorageError("Database connection unavailable.") from None

    def migrate(self, domain=None):
        from .migrations import migrate
        if self.settings.path is not None:
            self.settings.path.parent.mkdir(parents=True, exist_ok=True)
        migrate(self, domain)

    def healthy(self):
        try:
            conn = self.connect()
            try:
                return conn.execute("SELECT 1").fetchone()[0] == 1
            finally:
                conn.close()
        except Exception:
            return False

    def close(self):
        with self._lock:
            self._closed = True
            if self.pool is not None:
                pool = self.pool
                self.pool = None
                try:
                    pool.close()
                except Exception:
                    raise StorageError("Database shutdown failed.") from None


def database_for(value):
    if isinstance(value, Database):
        return value
    if isinstance(value, DatabaseSettings):
        return Database(value)
    if isinstance(value, Path):
        return Database(DatabaseSettings("", value))
    return Database(parse_database_settings(value))


def table_exists(conn, table):
    if isinstance(conn, PostgresConnection):
        return conn.execute("SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name=?", (table,)).fetchone() is not None
    return conn.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)).fetchone() is not None


def table_columns(conn, table):
    if isinstance(conn, PostgresConnection):
        return [row[0] for row in conn.execute("SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=? ORDER BY ordinal_position", (table,))]
    return [row[1] for row in conn.execute(f"PRAGMA table_info({identifier(table)})")]


def table_names(conn):
    if isinstance(conn, PostgresConnection):
        return [row[0] for row in conn.execute("SELECT table_name FROM information_schema.tables WHERE table_schema=current_schema() AND table_type='BASE TABLE' ORDER BY table_name")]
    return [row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")]
