"""Public product story describing supported workflows without fabricated results."""
from html import escape


def landing_html(authenticated: bool = False) -> str:
    secondary = 'Open Dashboard' if authenticated else 'Sign In'
    target = '/dashboard' if authenticated else '/login'
    markets = [('EU', 'TED', 'Public notices'), ('UK', 'Find a Tender', 'Public notices'), ('CA', 'CanadaBuys', 'Public data'), ('AU', 'AusTender', 'Public notices'), ('NZ', 'GETS', 'Public notices'), ('ZA', 'eTenders', 'Public data'), ('IN', 'CPPP', 'Public notices'), ('RU', 'EIS', 'Configured feeds'), ('US', 'SAM.gov', 'Credentials required'), ('KZ', 'Goszakup', 'Credentials required')]
    coverage = ''.join(f'<div class="market"><span>{code}</span><div><strong>{escape(name)}</strong><small>{note}</small></div></div>' for code, name, note in markets)
    steps = [('Discover', 'Explore official procurement sources.'), ('Match', 'Compare metadata with your company.'), ('Analyze', 'Review documents through supported workflows.'), ('Decide', 'Use evidence, completeness and fit.'), ('Win', 'Pursue the right opportunities. Outcomes are never guaranteed.')]
    workflow = ''.join(f'<article><span class="step-number">0{i}</span><h3>{title}</h3><p>{text}</p></article>' for i, (title, text) in enumerate(steps, 1))
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VALYQON AI · Global Procurement Intelligence</title><link rel="stylesheet" href="/assets/saas.css"><link rel="stylesheet" href="/assets/premium.css"><link rel="stylesheet" href="/assets/responsive.css?v=phase24q"></head>
<body class="landing premium"><a class="skip-link" href="#content">Skip to content</a>
<header class="landing-top"><a class="brand" href="/">VALYQON<span> AI</span></a><nav aria-label="Product navigation"><a href="#product">Product</a><a href="#coverage">Coverage</a><a href="#intelligence">Intelligence</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><div class="toolbar"><a href="{target}">{secondary}</a><a class="cta compact" href="/dashboard#discover">Find Opportunities</a></div></header>
<main id="content"><section class="hero premium-hero"><div><span class="eyebrow">Global Procurement Intelligence powered by AI</span><h1>Find. Analyze.<br><span>Score. Win.</span></h1><p>Find official opportunities across markets. Match them to your business. Give your team a clearer view of what deserves attention.</p><div class="toolbar"><a class="cta" href="/dashboard#discover">Find Opportunities <span aria-hidden="true">↗</span></a><a class="secondary" href="#workflow">See how it works</a></div><p class="fine">Company-specific insight. Evidence before decisions.</p></div>
<aside class="product-preview" aria-label="Discovery workflow"><div class="preview-top"><span class="eyebrow">OPPORTUNITY WORKSPACE</span><span class="preview-label">How discovery works</span></div><div class="preview-body"><h2>Review official opportunities</h2><p>Run a search from your shared company workspace to see available procurement notices.</p><div class="preview-criteria"><div><span>Company fit</span><span>Based on available metadata</span></div><div><span>Source status</span><span>Reported for each search</span></div><div><span>Missing information</span><span>Shown alongside the results</span></div><div><span>Document analysis</span><span>Upload a tender PDF in Discover or Saved</span></div></div><a href="/dashboard#discover" class="preview-link">Explore the discovery workspace <span aria-hidden="true">&rarr;</span></a><small class="fine">No search has been run here. No opportunity results or scores are displayed.</small></div></aside></section>
<div class="trust-strip"><span>Official procurement sources</span><span>Multi-country coverage</span><span>Company-specific matching</span><span>Explainable scoring</span></div>
<section class="content-section" id="workflow"><div class="section-heading"><span class="eyebrow">A FOCUSED WORKFLOW</span><h2>From a broad market<br>to a considered decision.</h2></div><div class="workflow-steps">{workflow}</div></section>
<section id="product" class="content-section product-grid"><div><span class="eyebrow">MORE THAN KEYWORD SEARCH</span><h2>Your company is<br>the starting point.</h2><p class="lede">A notice is only useful in context. Bring your products, markets and commercial constraints into the same workspace.</p><a class="text-link" href="/dashboard#companies">Build your company profile →</a></div><div class="profile-preview"><div class="preview-label">Product preview</div><h3>Company Match</h3><div class="profile-inputs"><span>Products &amp; services</span><span>Target markets</span><span>Currencies</span><span>Contract range</span><span>Search keywords</span><span>Capabilities</span></div><div class="match-output"><span aria-hidden="true">↓</span><strong>Preliminary company fit</strong><p>Criteria, available evidence and missing information — separately visible.</p></div></div></section>
<section id="coverage" class="content-section coverage-section"><div class="section-heading"><span class="eyebrow">GLOBAL DISCOVER</span><h2>Multi-country procurement coverage</h2><p>Integrated adapters, not a promise that every source is always available. Access, configuration and source health determine each search.</p></div><div class="market-grid">{coverage}</div><p class="fine">Authenticated sources remain disabled without configured credentials. No live availability or usage metrics are shown here.</p></section>
<section id="intelligence" class="content-section"><div class="section-heading"><span class="eyebrow">INTELLIGENCE WITH BOUNDARIES</span><h2>Know what the evidence says.<br>And what it does not.</h2></div><div class="intelligence-grid"><article><span class="source-pill">Available in discovery</span><h3>Company Match</h3><p>Preliminary fit, scoring criteria and data completeness from source metadata.</p><div class="evidence-line"><span>Evidence</span><span>Missing information</span></div></article><article><span class="neutral-pill">After document analysis</span><h3>Requirements &amp; risks</h3><p>The supported PDF workflow extracts structured facts and enables document-grounded questions. Discovery does not automatically import documents.</p></article><article><span class="neutral-pill">Future workflow</span><h3>Deeper opportunity intelligence</h3><p>Integrated document acquisition, richer eligibility and recommended action workflows are not enabled yet.</p></article></div></section>
<section class="content-section product-grid"><article class="feature"><span class="eyebrow">MONITORING</span><h2>A repeatable review rhythm.</h2><p>Run supported scans and inspect monitoring status. Configured personal Telegram alerts complement the web workspace; shared team notifications are a later step.</p><a href="/dashboard#monitoring">Review monitoring →</a></article><article class="feature"><span class="eyebrow">TEAM &amp; TELEGRAM</span><h2>Shared context. Explicit access.</h2><p>Organizations, roles and invitations support team workspaces. Telegram linking connects personal workflows. Server-side membership and session checks govern access.</p><a href="/dashboard#team">Explore team workspaces →</a></article></section>
<section id="pricing" class="content-section pricing-teaser"><div><span class="eyebrow">BUILT FOR FOCUSED TEAMS</span><h2>Explore the platform.<br>Commercial plans come later.</h2><p>Billing is not enabled. No payment details or checkout are collected here.</p></div><a class="secondary" href="/dashboard">Open the workspace →</a></section>
<section class="faq" id="faq"><h2>Clear answers before you begin.</h2><details><summary>Does a high fit score predict a win?</summary><p>No. It is preliminary company compatibility, not a probability of winning. Commercial decisions remain with your team.</p></details><details><summary>Is every tender fully analyzed?</summary><p>No. Discovery is a metadata preview. Full document analysis requires the supported PDF workflow.</p></details><details><summary>Can my team work together?</summary><p>Yes. Shared organizations provide company workspaces, roles and invitations. Viewer access remains read-only for mutations.</p></details><details><summary>Are all procurement sources always live?</summary><p>No. Some require credentials, and individual sources can be unavailable. Discovery reports partial failures explicitly.</p></details></section>
<section class="final-cta"><span class="eyebrow">VALYQON AI</span><h2>A better starting point<br>for your next opportunity.</h2><a class="cta" href="/dashboard#discover">Find Opportunities →</a></section></main><footer><a class="brand" href="/">VALYQON AI</a><span>Find. Analyze. Score. Win.</span><a href="#faq">Questions &amp; answers</a></footer></body></html>'''
