"""No external services: config, SQL, pool and offline import safety contracts."""
import io
import os
import sqlite3
from concurrent.futures import ThreadPoolExecutor
from contextlib import closing, redirect_stdout
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest

from app.database.backend import (
    Database, PostgresConnection, Row, StorageError, StorageIntegrityError,
    identifier, postgres_sql, table_columns, table_names,
)
from app.database.config import DatabaseConfigurationError, DatabaseSettings, load_database_settings, parse_database_settings
from app.database.import_sqlite import TABLES, import_sqlite, main, preflight_source
from app.database.migrations import MIGRATIONS


@pytest.mark.parametrize("url", ["postgresql://user:secret@localhost/test", "postgres://localhost/test", "postgresql://localhost:5432/test?sslmode=require"])
def test_postgres_config_supported_without_driver_import(url):
    settings = parse_database_settings(url)
    assert settings.backend == "postgresql" and settings.path is None
    assert "secret" not in repr(settings) and "localhost" not in repr(settings)


@pytest.mark.parametrize("url", ["postgresql://user:secret@localhost:bad/test", "postgresql://localhost", "mysql://user:secret@host/db", "sqlite://host/db", "sqlite:///db?password=secret", ""])
def test_config_rejects_bad_urls_without_secrets(url):
    with pytest.raises(DatabaseConfigurationError) as error:
        parse_database_settings(url)
    assert "secret" not in str(error.value)
    if url:
        assert url not in str(error.value)


def test_sqlite_path_and_production_postgres_requirement(tmp_path):
    assert parse_database_settings(str(tmp_path / "test.db")).path == tmp_path / "test.db"
    with pytest.raises(DatabaseConfigurationError):
        parse_database_settings("sqlite:///./test.db", require_postgres=True)
    with patch.dict(os.environ, {"VALYQON_DATABASE_REQUIRE_POSTGRES": "true", "DATABASE_URL": "sqlite:///./test.db"}, clear=True):
        with pytest.raises(DatabaseConfigurationError):
            load_database_settings(tmp_path / "absent.env")


@pytest.mark.parametrize("bounds", [(2, 1, 10), (-1, 10, 10), (0, 0, 10), (1, 101, 10), (1, 10, 0)])
def test_pool_bounds_validated(bounds):
    with pytest.raises(DatabaseConfigurationError):
        parse_database_settings("postgresql://localhost/test", pool_min=bounds[0], pool_max=bounds[1], pool_timeout=bounds[2])


def test_dialect_literals_parameters_conflict_and_types():
    assert postgres_sql("SELECT '?' AS literal WHERE id=?") == "SELECT '?' AS literal WHERE id=%s"
    assert postgres_sql("SELECT 'INTEGER % ?' WHERE id=?") == "SELECT 'INTEGER %% ?' WHERE id=%s"
    assert postgres_sql("INSERT OR IGNORE INTO monitor_seen VALUES (?)").endswith("VALUES (%s) ON CONFLICT DO NOTHING")
    sql = postgres_sql("CREATE TABLE x(id INTEGER PRIMARY KEY AUTOINCREMENT, owner INTEGER, data BLOB, flag INTEGER CHECK(flag IN (0,1)))")
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in sql and "BYTEA" in sql
    assert "AUTOINCREMENT" not in sql and "INTEGER" not in sql
    assert "ON CONFLICT" in postgres_sql("INSERT INTO x VALUES (?) ON CONFLICT(id) DO UPDATE SET id=excluded.id")
    with pytest.raises(StorageError):
        identifier('x; DELETE FROM auth_accounts')


def test_every_frozen_schema_compiles_without_sqlite_features():
    for migration in MIGRATIONS:
        sql = postgres_sql(migration.sql, parameters=False)
        assert not any(keyword in sql for keyword in ("AUTOINCREMENT", "COLLATE NOCASE", " BLOB", "PRAGMA"))


class FakeRaw:
    def __init__(self):
        self.calls = []
        self.commits = self.rollbacks = self.closes = 0
        self.fail = None

    def execute(self, sql, params=None):
        self.calls.append((sql, params))
        if self.fail:
            raise self.fail
        result = MagicMock()
        result.rowcount = 1
        result.fetchone.return_value = {"id": 42} if "RETURNING" in sql else {"value": 1}
        result.fetchall.return_value = [{"id": 42}]
        return result

    def cursor(self):
        return MagicMock()

    def commit(self):
        self.commits += 1

    def rollback(self):
        self.rollbacks += 1

    def close(self):
        self.closes += 1


class FakePool:
    def __init__(self, **kwargs):
        self.kwargs = kwargs
        self.raw = FakeRaw()
        self.returned = []
        self.opened = self.closed = 0

    def open(self, **kwargs):
        self.opened += 1

    def getconn(self, **kwargs):
        return self.raw

    def putconn(self, raw):
        self.returned.append(raw)

    def close(self):
        self.closed += 1


def fake_database(factory=FakePool):
    return Database(parse_database_settings("postgresql://user:secret@localhost/test", pool_min=2, pool_max=5), pool_factory=factory)


def test_pool_reuse_insert_ids_safe_release_shutdown():
    database = fake_database()
    database.open()
    pool = database.pool
    assert pool.kwargs["min_size"] == 2 and pool.kwargs["max_size"] == 5
    assert pool.opened == 1
    with closing(database.connect()) as conn:
        with conn:
            conn.execute("BEGIN IMMEDIATE")
            cursor = conn.execute("INSERT INTO auth_accounts(email) VALUES (?)", ("synthetic@example.test",))
            assert cursor.lastrowid == 42
            assert "RETURNING id" in pool.raw.calls[-1][0]
            assert pool.raw.calls[-1][1] == ("synthetic@example.test",)
    assert pool.raw.commits == 1 and pool.raw.rollbacks == 1
    assert len([sql for sql, _ in pool.raw.calls if "pg_advisory_xact_lock" in sql]) == 1
    with closing(database.connect()) as conn:
        assert conn.execute("SELECT 1").fetchone()[0] == 1
    assert pool.opened == 1 and len(pool.returned) == 2
    database.close()
    database.close()
    assert pool.closed == 1
    with pytest.raises(StorageError):
        database.connect()


def test_pool_failed_transaction_rolls_back_and_redacts():
    database = fake_database()
    database.open()
    pool = database.pool
    with closing(database.connect()) as conn:
        with pytest.raises(StorageError) as error:
            with conn:
                pool.raw.fail = RuntimeError("user secret postgres://host")
                conn.execute("UPDATE auth_accounts SET email=?", ("synthetic",))
        assert "secret" not in str(error.value)
    assert pool.raw.commits == 0 and pool.raw.rollbacks == 2 and len(pool.returned) == 1
    database.close()


def test_pool_constraint_error_mapping():
    class FakeIntegrityError(Exception):
        pass
    database = fake_database()
    database.open()
    database.integrity_error = FakeIntegrityError
    database.pool.raw.fail = FakeIntegrityError("password_hash=secret")
    with closing(database.connect()) as conn:
        with pytest.raises(StorageIntegrityError, match="constraint violation"):
            conn.execute("INSERT INTO organization_members VALUES (?)", (1,))
    database.close()


def test_pool_failure_never_falls_back_and_closes_partial_pool():
    pool = FakePool()
    pool.open = MagicMock(side_effect=RuntimeError("secret@host"))
    database = fake_database(lambda **kwargs: pool)
    with pytest.raises(StorageError) as error:
        database.connect()
    assert "secret" not in str(error.value) and "host" not in str(error.value)
    assert database.pool is None and pool.closed == 1


def test_dirty_broken_connection_is_closed_before_return():
    database = fake_database()
    database.open()
    pool = database.pool
    pool.raw.rollback = MagicMock(side_effect=RuntimeError("secret"))
    conn = database.connect()
    conn.close()
    conn.close()
    assert pool.raw.closes == 1 and len(pool.returned) == 1
    database.close()


def test_shutdown_allows_outstanding_lease_to_return():
    database = fake_database()
    conn = database.connect()
    pool = database.pool
    database.close()
    conn.close()
    assert pool.closed == 1 and pool.returned == [pool.raw]


def test_pool_initialization_is_thread_safe():
    factory = MagicMock(side_effect=FakePool)
    database = fake_database(factory)
    with ThreadPoolExecutor(max_workers=4) as executor:
        list(executor.map(lambda _: database.open(), range(4)))
    assert factory.call_count == 1 and database.pool.opened == 1
    database.close()


def test_health_checks_live_connection_and_only_returns_status():
    database = fake_database()
    assert database.healthy() is True
    database.pool.raw.fail = RuntimeError("secret@host")
    assert database.healthy() is False
    database.close()


def test_fastapi_shutdown_closes_owned_database():
    from fastapi.testclient import TestClient
    from app.api.main import create_app
    from app.api.config import ApiSettings
    from app.api.runtime import ApiRuntime
    database = fake_database()
    database.open()
    pool = database.pool
    runtime = ApiRuntime(database=database)
    with patch("app.api.main.build_runtime", return_value=runtime) as build, patch.object(runtime, "close", wraps=runtime.close) as close:
        app = create_app(settings=ApiSettings("127.0.0.1", 8000, False))
        with TestClient(app):
            assert app.state.runtime is runtime
            build.assert_called_once_with()
            close.assert_not_called()
            assert pool.closed == 0
        close.assert_called_once_with()
    assert pool.closed == 1


@pytest.mark.parametrize("has_close", [False, True])
def test_fastapi_shutdown_does_not_own_injected_runtime(has_close):
    from fastapi.testclient import TestClient
    from app.api.main import create_app
    from app.api.config import ApiSettings
    runtime = SimpleNamespace()
    if has_close:
        runtime.close = MagicMock()
    with patch("app.api.main.build_runtime") as build:
        app = create_app(runtime=runtime, settings=ApiSettings("127.0.0.1", 8000, False))
        with TestClient(app):
            assert app.state.runtime is runtime
        build.assert_not_called()
    if has_close:
        runtime.close.assert_not_called()
    else:
        assert not hasattr(runtime, "close")


def test_runtime_postgres_startup_failure_closes_without_fallback():
    from app.api.runtime import build_runtime
    with patch("app.database.load_database_settings", return_value=parse_database_settings("postgresql://host/db")), patch.object(Database, "migrate", side_effect=RuntimeError("secret")), patch.object(Database, "close") as close:
        with pytest.raises(StorageError, match="startup failed"):
            build_runtime()
    close.assert_called_once()


@pytest.fixture
def sqlite_database(tmp_path):
    database = Database(DatabaseSettings("", tmp_path / "source.db"))
    database.migrate()
    yield database
    database.close()


def test_fresh_schema_order_version_and_idempotency(sqlite_database):
    sqlite_database.migrate()
    with closing(sqlite_database.connect()) as conn:
        rows = conn.execute("SELECT version,domain,checksum FROM app_schema_migrations ORDER BY version").fetchall()
        assert [tuple(row) for row in rows] == [(m.version, m.domain, m.checksum) for m in MIGRATIONS]
        assert conn.execute("PRAGMA foreign_key_check").fetchall() == []
        assert set(TABLES) <= set(table_names(conn))


def test_migration_failure_is_atomic(tmp_path):
    database = Database(DatabaseSettings("", tmp_path / "failed.db"))
    from app.database import migrations
    real_apply = migrations._apply
    def fail(conn, migration, backend):
        if migration.version == 2:
            raise StorageError("synthetic migration failure")
        real_apply(conn, migration, backend)
    with patch.object(migrations, "_apply", fail), pytest.raises(StorageError):
        database.migrate()
    with closing(database.connect()) as conn:
        assert table_names(conn) == []
    database.close()


@pytest.mark.parametrize("modification", ["UPDATE app_schema_migrations SET checksum='changed' WHERE version=1", "INSERT INTO app_schema_migrations VALUES(99,'future','x')", "UPDATE schema_meta SET value='99'"])
def test_unknown_or_changed_schema_fails_cleanly(sqlite_database, modification):
    with closing(sqlite_database.connect()) as conn, conn:
        conn.execute(modification)
    # Legacy schema version must also be checked on repeated startup.
    with pytest.raises(StorageError):
        sqlite_database.migrate()


def test_legacy_schema_is_upgraded_without_losing_ids_or_hashes(tmp_path):
    path = tmp_path / "legacy.db"
    with closing(sqlite3.connect(path)) as conn:
        conn.executescript("""CREATE TABLE auth_accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL COLLATE NOCASE UNIQUE,password_hash TEXT NOT NULL,owner_user_id INTEGER UNIQUE,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
        INSERT INTO auth_accounts VALUES(42,'synthetic@example.test','synthetic_hash',4000000000042,1,'old','old');""")
    database = Database(DatabaseSettings("", path))
    database.migrate()
    with closing(database.connect()) as conn:
        row = conn.execute("SELECT id,password_hash,email_verified FROM auth_accounts").fetchone()
        assert tuple(row) == (42, "synthetic_hash", 1)
        assert conn.execute("SELECT personal_account_id FROM organizations").fetchone()[0] == 42
    database.close()


class ImportDestinationFixture:
    """SQLite-backed algorithm fixture; this is explicitly NOT PostgreSQL integration."""
    backend = "postgresql"
    def __init__(self, database, *, fail_table=None):
        self.database = database
        self.fail_table = fail_table
        self.statements = []

    def connect(self):
        fixture = self
        raw = self.database.connect()
        class Connection:
            def execute(self, sql, params=()):
                fixture.statements.append(sql)
                if "setval(" in sql:
                    return raw.execute("SELECT 1")
                return raw.execute(sql, params)
            def executemany(self, sql, rows):
                if fixture.fail_table and fixture.fail_table in sql:
                    raise StorageError("synthetic import failure")
                return raw.executemany(sql, rows)
            def __enter__(self):
                raw.__enter__()
                return self
            def __exit__(self, *args):
                return raw.__exit__(*args)
            def close(self):
                raw.close()
        return Connection()


def seeded_source(database):
    from app.auth import AuthRepository
    from app.organizations import OrganizationRepository
    from app.companies import CompanyRepository
    from app.database.repository import TenderRepository
    from app.monitoring import MonitoringRepository
    from app.scoring.models import CompanyProfile
    from app.models.tender import TenderAnalysis
    from app.rag.store import SQLiteVectorStore
    from app.rag.models import DocumentChunk
    auth = AuthRepository(database)
    account = auth.create_account("synthetic@example.test", "synthetic-password-hash")
    auth.create_session(token_hash="synthetic-session-hash", account_id=account.id, expires_at="2099-01-01T00:00:00+00:00")
    auth.create_password_reset(account_id=account.id, token_hash="synthetic-reset-hash", expires_at="2099-01-01T00:00:00+00:00")
    org = OrganizationRepository(database).default_for_account(account.id)
    company = CompanyRepository(database).create_for_organization(account_id=account.id, organization_id=org.id, name="Synthetic", profile=CompanyProfile(profile_version="1", company_name="Synthetic", business_mode="sell"))
    tenders = TenderRepository(database)
    tenders.save_opportunity_for_organization(account_id=account.id, organization_id=org.id, company_id=company.id, source="synthetic", external_id="one", snapshot_json='{"synthetic":true}')
    tenders.save_success(owner_user_id=account.owner_user_id, chat_id=account.owner_user_id, pdf_sha256="a" * 64, source_filename="synthetic.pdf", pages=1, characters=12, analysis=TenderAnalysis(title="Synthetic"), scoring=None, analysis_truncated=False)
    MonitoringRepository(database).mark_seen(account.owner_user_id, "synthetic", "one")
    MonitoringRepository(database).set_subscription(account.owner_user_id, account.owner_user_id, True)
    auth.create_email_verification(account_id=account.id, token_hash="synthetic-verification-hash", expires_at="2099-01-01T00:00:00+00:00")
    auth.create_telegram_link(account_id=account.id, token_hash="synthetic-telegram-hash", expires_at="2099-01-01T00:00:00+00:00")
    from app.organizations import Role
    OrganizationRepository(database).create_invitation_authorized(actor_account_id=account.id, organization_id=org.id, email="synthetic-invite@example.test", role=Role.MEMBER, token_hash="synthetic-invitation-hash", expires_at="2099-01-01T00:00:00+00:00")
    tenders.record_discovery_search_for_organization(account_id=account.id, organization_id=org.id, company_id=company.id, result_count=1, scored_count=0, attempted_sources_json='["synthetic"]', successful_sources_json='["synthetic"]', failed_sources_json="[]", partial_failure=False, total_failure=False, snapshot_json="{}")
    SQLiteVectorStore(database, 2).replace_document(account.owner_user_id, "a" * 64, [(DocumentChunk(0, 1, "synthetic chunk"), (0.25, 0.75))])
    from app.support import SupportRepository
    support = SupportRepository(database)
    ticket = support.create_ticket(owner_user_id=account.owner_user_id, account_id=account.id, first_name="Synthetic", last_name="Fixture", email=account.email, category="technical", subject="Synthetic", description="Synthetic fixture", priority="normal", organization_id=org.id, company_id=company.id, page_path="/synthetic", app_version="synthetic", browser="synthetic")
    with closing(database.connect()) as conn, conn:
        conn.execute("INSERT INTO support_ticket_messages(ticket_id,author_type,author_account_id,author_email,body,created_at) VALUES(?,'user',?,?,?,?)", (ticket.id, account.id, account.email, "synthetic message", "2026-01-01T01:02:03.456789+00:00"))
    return account, org, company


def empty_destination(tmp_path):
    database = Database(DatabaseSettings("", tmp_path / "destination.db"))
    database.migrate()
    return database


def test_import_dry_run_preserves_source_and_destination(sqlite_database, tmp_path):
    seeded_source(sqlite_database)
    destination = empty_destination(tmp_path)
    try:
        before = sqlite_database.settings.path.read_bytes(), destination.settings.path.read_bytes()
        fixture = ImportDestinationFixture(destination)
        counts = import_sqlite(sqlite_database.settings.path, fixture, dry_run=True)
        assert counts["auth_accounts"] == 1
        assert before == (sqlite_database.settings.path.read_bytes(), destination.settings.path.read_bytes())
        assert not any(sql.startswith(("INSERT", "CREATE", "BEGIN")) or "setval(" in sql for sql in fixture.statements)
    finally:
        destination.close()


def test_import_preserves_every_value_and_refuses_second_execution(sqlite_database, tmp_path):
    seeded_source(sqlite_database)
    destination = empty_destination(tmp_path)
    try:
        fixture = ImportDestinationFixture(destination)
        counts = import_sqlite(sqlite_database.settings.path, fixture, dry_run=False)
        with closing(sqlite_database.connect()) as source, closing(destination.connect()) as target:
            for table in TABLES:
                assert [tuple(row) for row in source.execute(f'SELECT * FROM "{table}"')] == [tuple(row) for row in target.execute(f'SELECT * FROM "{table}"')]
                assert target.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] == counts[table]
            assert target.execute("PRAGMA foreign_key_check").fetchall() == []
        with pytest.raises(StorageError, match="already been imported"):
            import_sqlite(sqlite_database.settings.path, fixture, dry_run=False)
    finally:
        destination.close()


def test_import_failure_rolls_back_all_data_and_marker(sqlite_database, tmp_path):
    seeded_source(sqlite_database)
    destination = empty_destination(tmp_path)
    try:
        with pytest.raises(StorageError):
            import_sqlite(sqlite_database.settings.path, ImportDestinationFixture(destination, fail_table="company_workspaces"), dry_run=False)
        with closing(destination.connect()) as conn:
            for table in (*TABLES, "app_data_imports"):
                assert conn.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] == 0
    finally:
        destination.close()


def test_import_count_mismatch_rolls_back(sqlite_database, tmp_path):
    seeded_source(sqlite_database)
    destination = empty_destination(tmp_path)
    real_preflight = preflight_source
    def incorrect_count(conn):
        columns, counts = real_preflight(conn)
        counts["auth_accounts"] += 1
        return columns, counts
    try:
        with patch("app.database.import_sqlite.preflight_source", incorrect_count), pytest.raises(StorageError, match="row-count mismatch"):
            import_sqlite(sqlite_database.settings.path, ImportDestinationFixture(destination), dry_run=False)
        with closing(destination.connect()) as conn:
            assert conn.execute("SELECT COUNT(*) FROM auth_accounts").fetchone()[0] == 0
            assert conn.execute("SELECT COUNT(*) FROM app_data_imports").fetchone()[0] == 0
    finally:
        destination.close()


def test_import_preflight_rejects_foreign_key_damage(sqlite_database):
    with closing(sqlite3.connect(sqlite_database.settings.path)) as conn, conn:
        conn.execute("INSERT INTO auth_sessions VALUES('synthetic',999,'2099','2026','2026')")
    with closing(sqlite_database.connect()) as conn, pytest.raises(StorageError, match="foreign-key"):
        preflight_source(conn)


def test_import_preflight_rejects_missing_primary_key(sqlite_database):
    with closing(sqlite_database.connect()) as conn, conn:
        conn.execute("DROP TABLE auth_sessions")
        conn.execute("CREATE TABLE auth_sessions(token_hash TEXT,account_id INTEGER,expires_at TEXT,created_at TEXT,last_seen_at TEXT)")
    with closing(sqlite_database.connect()) as conn, pytest.raises(StorageError, match="primary keys"):
        preflight_source(conn)


def test_import_refuses_populated_destination(sqlite_database, tmp_path):
    destination = empty_destination(tmp_path)
    try:
        seeded_source(destination)
        with pytest.raises(StorageError, match="must be empty"):
            import_sqlite(sqlite_database.settings.path, ImportDestinationFixture(destination), dry_run=False)
    finally:
        destination.close()


@pytest.mark.parametrize("mutation", ["CREATE TABLE unknown_data(id INTEGER)", "UPDATE schema_meta SET value='99'", "ALTER TABLE auth_accounts ADD COLUMN unsupported TEXT", "DROP TABLE auth_sessions"])
def test_import_source_preflight_rejects_unsupported_schema(sqlite_database, mutation):
    with closing(sqlite_database.connect()) as conn, conn:
        conn.execute(mutation)
    with closing(sqlite_database.connect()) as conn, pytest.raises(StorageError):
        preflight_source(conn)


def test_import_requires_existing_source_and_postgres_destination(sqlite_database, tmp_path):
    with pytest.raises(StorageError, match="PostgreSQL"):
        import_sqlite(sqlite_database.settings.path, sqlite_database)
    with pytest.raises(StorageError, match="does not exist"):
        import_sqlite(tmp_path / "absent.db", SimpleNamespace(backend="postgresql"))
    assert not (tmp_path / "absent.db").exists()


def test_import_cli_redacts_unexpected_errors(tmp_path):
    output = io.StringIO()
    with patch("app.database.import_sqlite.load_database_settings", side_effect=RuntimeError("secret-password-hash-session-token")), redirect_stdout(output):
        assert main(["--source", str(tmp_path / "test.db"), "--dry-run"]) == 1
    assert "secret" not in output.getvalue() and "token" not in output.getvalue()


def test_concurrent_account_email_and_one_time_reset(sqlite_database):
    from app.auth import AuthRepository, AuthRepositoryError
    auth = AuthRepository(sqlite_database)
    def register(_):
        try:
            return auth.create_account("synthetic@example.test", "synthetic-hash")
        except AuthRepositoryError:
            return None
    with ThreadPoolExecutor(max_workers=4) as executor:
        accounts = list(executor.map(register, range(4)))
    account = next(account for account in accounts if account)
    assert sum(account is not None for account in accounts) == 1
    auth.create_session(token_hash="synthetic-session", account_id=account.id, expires_at="2099")
    auth.create_password_reset(account_id=account.id, token_hash="synthetic-reset", expires_at="2099")
    with ThreadPoolExecutor(max_workers=4) as executor:
        results = list(executor.map(lambda _: auth.consume_password_reset(token_hash="synthetic-reset", password_hash="synthetic-new-hash", now="2026"), range(4)))
    assert sum(result is not None for result in results) == 1
    with closing(sqlite_database.connect()) as conn:
        assert conn.execute("SELECT COUNT(*) FROM auth_sessions").fetchone()[0] == 0
        assert conn.execute("SELECT COUNT(*) FROM organizations").fetchone()[0] == 1


def test_concurrent_saved_opportunity_and_monitor_claim(sqlite_database):
    from app.database.repository import TenderRepository
    from app.monitoring import MonitoringRepository
    account, org, company = seeded_source(sqlite_database)
    repository = TenderRepository(sqlite_database)
    monitor = MonitoringRepository(sqlite_database)
    def save(_):
        return repository.save_opportunity_for_organization(account_id=account.id, organization_id=org.id, company_id=company.id, source="synthetic", external_id="concurrent", snapshot_json="{}")
    with ThreadPoolExecutor(max_workers=4) as executor:
        saved = list(executor.map(save, range(4)))
        claimed = list(executor.map(lambda _: monitor.mark_seen(account.owner_user_id, "synthetic", "concurrent"), range(4)))
    assert len({item.id for item in saved}) == 1 and sum(claimed) == 1
