const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(process.argv[2],'utf8');const script=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/refreshAll\(\)\.catch\([\s\S]*$/, '');
const nodes={};const values={companyName:'New name',keywords:'steel',searchKeywords:'steel plate',countries:'Germany',currencies:'EUR, USD',documentsAvailable:'ISO 9001',regions:'Berlin',industry:'Manufacturing',excludedKeywords:'used',minContract:'',maxContract:'1000',businessMode:'sell'};
function node(id){return nodes[id]??={value:values[id]??'',textContent:'',innerHTML:'',disabled:false,classList:{add(){},remove(){}},focus(){}};}
const context={document:{getElementById:node},window:{addEventListener(){},dispatchEvent(){}},location:{hash:''},Event:function(){},URL,Date,setTimeout,clearTimeout,Headers,FormData,AbortController};
vm.runInNewContext(script,context);
vm.runInNewContext(`state.organizations=[{id:11,personal:false}];state.organizationId=11;state.organizationRole='owner';state.editCompanyId=5;state.editProfile={profile_version:'old',max_bid_security_percent:9,hard_stop_on_bid_security:true,max_contract_security_percent:7,hard_stop_on_contract_security:true,hard_stop_on_region:false};calls=[];api=async(p,o)=>{calls.push({p,o});return {id:5}};loadCompanies=async()=>{};loadMonitoring=async()=>{};`,context);
(async()=>{await vm.runInNewContext('createCompany()',context);const call=context.calls[0];assert.equal(call.p,'/api/v1/organizations/11/companies/5');assert.equal(call.o.method,'PATCH');const body=JSON.parse(call.o.body);assert.equal(body.profile.max_bid_security_percent,9);assert.equal(body.profile.max_contract_security_percent,7);assert.equal(body.profile.hard_stop_on_bid_security,true);assert.equal(body.profile.hard_stop_on_region,false);assert.deepEqual(body.profile.search_keywords,['steel plate']);assert.deepEqual(body.profile.accepted_currencies,['EUR','USD']);
vm.runInNewContext("state.organizationRole='viewer';calls=[]",context);await vm.runInNewContext('createCompany()',context);assert.equal(context.calls.length,0);console.log('Profile preservation and viewer mutation guard passed');})().catch(e=>{console.error(e);process.exitCode=1});
